function LocalName({ local, zh }: { local: string; zh: string }) {
  return <span className="bilingual-name"><span lang="ja">{local}</span><small>{zh}</small></span>;
}

function Note({ children, no }: { children: React.ReactNode; no: string }) {
  return <aside className="margin-note"><span>{no}</span><p>{children}</p></aside>;
}

export default function KyotoGuide({ theme }: { theme: "vintage" | "modern" }) {
  return (
    <div className="book-pages kyoto-book">
      <header className="masthead"><div className="crumb"><span>日本</span><i>◆</i><span>京都府</span><i>◆</i><b>京都</b></div><p>{theme === "modern" ? "写真版 · 现代影像版" : "旅人のための版 · 旅行者版本"}</p></header>

      <section id="prologue" className="chapter hero-chapter">
        <div className="hero-title"><p className="eyebrow">季節を一服ずつ味わう町</p><h2><span lang="ja">Kyoto</span><small>京都</small></h2><p className="hero-subtitle">木檐接住雨，庭院把时间留白</p></div>
        <figure className="hero-figure"><img src={theme === "modern" ? "/images/kyoto-hero-modern.png" : "/images/kyoto-hero-vintage.png"} alt={theme === "modern" ? "生成的现代旅行摄影风格京都清水寺舞台与东山" : "复古木版画风格的京都清水寺舞台、东山与城市"} /><figcaption><b>图版 I</b><span><i lang="ja">清水寺と東山</i> · 清水寺与东山</span><small>木构舞台伸向山林，屋檐之下，京都把远景与季节一同收进来。</small></figcaption></figure>
        <div className="prologue-grid"><div className="lead-copy"><span className="drop-cap">京</span><p>都不靠速度制造惊喜。门帘轻轻掀起，石钵里落下一滴水，格栅后的灯在薄暮中慢慢变暖——城市把重要的部分藏在动作与停顿之间。寺院与神社只是框架，真正变化的是苔、枫、樱与光。</p><p>把清晨留给东山或伏见，避开人潮也避免打扰居民；午后去庭园、工艺店与茶屋，傍晚沿鸭川散步。京都需要的不是更多清单，而是一双愿意放轻的脚。</p></div><blockquote><span>“</span><p lang="ja">京都では、静けさにも季節の色がある。</p><small>在京都，连寂静也有季节的颜色。</small></blockquote><div className="fact-card"><p className="fact-label">旅の入口 · 扉页速览</p><dl><div><dt>最佳步调</dt><dd>3—4 日</dd></div><div><dt>城市气质</dt><dd>克制、细腻、季节感</dd></div><div><dt>适合时节</dt><dd>四季皆宜</dd></div><div><dt>不可错过</dt><dd>清晨走进东山</dd></div></dl></div></div>
      </section>

      <section id="cultura" className="chapter chapter-cultura">
        <div className="chapter-heading"><p>第一章 · CHAPTER ONE</p><h2><span lang="ja">文化</span><small>人文 · 山门与町家</small></h2><span className="page-no">01</span></div>
        <article className="feature-duomo"><div className="feature-number">一</div><div><p className="category">舞台と眺望 · 木构与远景</p><h3><LocalName local="清水寺" zh="清水寺" /></h3><p className="standfirst">十三米高的木柱托起著名舞台，视线越过东山树海，一直落向京都城。</p><div className="columns"><p>清水寺的本堂舞台依山而建，不使用钉子的传统木构把建筑与坡地紧密结合。穿过仁王门后，不妨放慢速度，观察檐口、柱网与城市远景如何随着脚步不断重组。</p><p>清晨更安静，也更适合继续步行二年坂、三年坂与祇园。狭窄街道仍连接着居民生活，请勿堵塞店门、追逐拍摄艺伎艺舞伎，或进入标明禁止通行的私巷。</p></div><div className="visit-strip"><span><b>建议</b> 开门后尽早抵达</span><span><b>留时</b> 2—3 小时</span><a href="https://kyoto.travel/en/destinations/kiyomizudera-temple/" target="_blank" rel="noreferrer">京都官方指南 ↗</a></div></div><Note no="13 M">清水舞台由约十三米高的木柱支撑；向西可俯瞰京都，尤其适合看日落。</Note></article>
        <div className="culture-mosaic"><article className="art-card last-supper"><p className="category">千本鳥居 · 千本鸟居</p><span className="art-index">02</span><h3><LocalName local="伏見稲荷大社" zh="伏见稻荷大社" /></h3><p>朱红鸟居从山脚一路叠向稻荷山。不要只在入口争抢同一张照片，继续上行，人群会渐渐变少，石狐、林荫与小祠让参拜路线恢复安静。</p><p className="tip">伏见拥有优质地下水和悠久酒造传统，可把神社与酒藏街区组合成半日。</p><a href="https://kyoto.travel/en/areas/fushimi/" target="_blank" rel="noreferrer">伏見 · FUSHIMI ↗</a></article><article className="art-card brera-card"><p className="category">庭と金箔 · 庭园与金箔</p><span className="art-index">03</span><h3><LocalName local="金閣寺" zh="金阁寺" /></h3><p>金色舍利殿在镜湖池中留下倒影。与其只看建筑，不如留意庭园如何用松、石、岛屿与借景控制观看顺序。</p></article><article className="art-card scala-card"><p className="category">城と障壁画 · 城郭与壁画</p><span className="art-index">04</span><h3><LocalName local="二条城" zh="二条城" /></h3><p>德川时代的权力通过唐门、御殿、金碧障壁画和“莺声地板”被转译为空间礼仪。</p></article><article className="art-card castle-card kyoto-machiya-card"><p className="category">暮らしの器 · 日常容器</p><span className="art-index">05</span><h3><LocalName local="祇園と町家" zh="祇园与町家" /></h3><p>狭长町家、格子立面与内庭回应了商业和生活需求。尊重私人空间，避开未经许可的近距离人物拍摄，街区才不是布景。</p></article></div>
      </section>

      <section id="natura" className="chapter chapter-natura">
        <div className="chapter-heading"><p>第二章 · CHAPTER TWO</p><h2><span lang="ja">自然</span><small>自然 · 竹影与川风</small></h2><span className="page-no">02</span></div>
        <div className="nature-layout"><figure className="navigli-figure"><img src={theme === "modern" ? "/images/kyoto-nature-modern.png" : "/images/kyoto-nature-vintage.png"} alt={theme === "modern" ? "生成的现代旅行摄影风格岚山桂川、渡月桥与竹林" : "复古木版画风格的岚山桂川、渡月桥与秋林"} /><figcaption><b>图版 II</b><span><i lang="ja">嵐山と桂川</i> · 岚山与桂川</span></figcaption></figure><article className="navigli-copy"><p className="category">山と川 · 山与河</p><h3><LocalName local="嵐山" zh="岚山" /></h3><p className="standfirst">桂川、渡月桥与群山共同完成一幅会随四季换色的长卷，竹林只是其中最响亮的一段。</p><p>清晨先走竹林与小径，再回到河岸看山色倒映水面；也可把注意力转向寺院庭园和保津峡方向。旺季拥挤明显，提前查看京都官方舒适度预测，错峰比寻找“无人机位”更有效。</p><div className="time-note"><span>07:00</span><p><b lang="ja">朝の川辺</b><small>河风与第一班电车之间</small></p></div></article><Note no="四季">春樱、夏绿、秋枫、冬雪各有气质；不要为了单一季节忽略清晨与天气。</Note></div>
        <div className="green-index"><article className="green-feature"><span className="botanical-mark">✦</span><p className="category">水辺の道 · 水边小径</p><h3><LocalName local="哲学の道" zh="哲学之道" /></h3><p>沿疏水渠延伸的步道连接银阁寺与南禅寺一带。樱季之外更安静，石桥、居民花园和小店让散步有细碎停顿。</p><p className="green-tip">从北向南步行，最后进入南禅寺或继续到冈崎。</p></article><article><span className="mini-no">N. 02</span><h3><LocalName local="京都御苑" zh="京都御苑" /></h3><p>宽阔林地包围京都御所，碎石路、老树与季节花木适合在市中心喘一口气。</p></article><article><span className="mini-no">N. 03</span><h3><LocalName local="鴨川" zh="鸭川" /></h3><p>傍晚坐在河岸，看骑行者、学生和水鸟共享同一条风道，是京都最不需要门票的日常。</p></article></div>
      </section>

      <section id="sapori" className="chapter chapter-sapori">
        <div className="chapter-heading dark-heading"><p>第三章 · CHAPTER THREE</p><h2><span lang="ja">味わい</span><small>美食 · 水与季节</small></h2><span className="page-no">03</span></div>
        <div className="food-spread"><figure><img src={theme === "modern" ? "/images/kyoto-food-modern.png" : "/images/kyoto-food-vintage.png"} alt={theme === "modern" ? "生成的现代美食摄影风格京都汤豆腐、会席料理、家常菜与抹茶和果子" : "复古木版画风格的京都季节餐桌"} /><figcaption><b>图版 III</b><span><i lang="ja">京の食卓</i> · 京都餐桌</span></figcaption></figure><div className="food-intro"><p className="category">水と季節 · 水与季节</p><h3>一只碗装下当季，<br />一杯茶留下余韵。</h3><p>京都长久作为都城，宫廷、寺院、茶道与町家共同塑造了细致的饮食文化。会席讲究顺序与季节，精进料理尊重植物本味，家常的御番菜则用炊煮与腌渍把日子过得耐吃。</p><p className="script-note" lang="ja">いただきます</p><small>“我开动了” · 用餐前表达感谢</small></div></div>
        <div className="dish-grid"><article className="dish-primary"><span className="dish-no">01</span><p className="category">豆腐 · TOFU</p><h3><LocalName local="湯豆腐" zh="汤豆腐" /></h3><p>昆布水中温热豆腐，以葱、酱油或柚子醋提味。看似清淡，真正考验水、豆香和温度，南禅寺一带尤为常见。</p></article><article><span className="dish-no">02</span><p className="category">おばんざい · 家常菜</p><h3><LocalName local="おばんざい" zh="京都家常菜" /></h3><p>用时令蔬菜、豆制品与干货做成多样小菜，滋味温和，却最能看见京都家庭如何安排一餐。</p></article><article><span className="dish-no">03</span><p className="category">菓子 · 甜点</p><h3><LocalName local="抹茶と和菓子" zh="抹茶与和果子" /></h3><p>和果子用形、色和铭名提前讲出季节，抹茶的苦味则把甜度收住；不必急着拍照，先吃最好的温度。</p></article><article className="aperitivo-card kyoto-tea-card"><span className="dish-no">15:00</span><p className="category">茶の時間 · 城市仪式</p><h3><LocalName local="一服のお茶" zh="一服茶的时间" /></h3><p>茶并非行程之间的饮料，而是一段完整的注意力。进店后收起响铃，观察器物与点心，再跟随主人的节奏慢下来。</p></article></div>
      </section>

      <section id="itinerario" className="chapter chapter-itinerary">
        <div className="chapter-heading"><p>第四章 · CHAPTER FOUR</p><h2><span lang="ja">旅程</span><small>行程 · 48 小时</small></h2><span className="page-no">04</span></div>
        <div className="route-days"><article><header><span>一日目</span><b>01</b><small>东山与伏见</small></header><ol><li><time>07:00</time><p><b lang="ja">清水寺</b><span>在街区醒来前看东山</span></p></li><li><time>10:30</time><p><b lang="ja">祇園・建仁寺</b><span>町家街道与寺院</span></p></li><li><time>14:00</time><p><b lang="ja">伏見稲荷大社</b><span>继续上行避开入口人潮</span></p></li><li><time>18:00</time><p><b lang="ja">鴨川</b><span>沿河走进夜色</span></p></li></ol></article><article><header><span>二日目</span><b>02</b><small>岚山与庭园</small></header><ol><li><time>07:00</time><p><b lang="ja">嵐山</b><span>竹林、河岸与山色</span></p></li><li><time>11:30</time><p><b lang="ja">湯豆腐</b><span>安静吃一顿午餐</span></p></li><li><time>14:30</time><p><b lang="ja">二条城</b><span>御殿、庭园与壁画</span></p></li><li><time>17:30</time><p><b lang="ja">京都御苑</b><span>老树下结束白昼</span></p></li></ol></article></div>
        <div className="phrasebook"><div><p className="category">旅のことば · 袖珍会话</p><h3 lang="ja">二人です。お願いします。</h3><p>两位，麻烦了。</p></div><dl><div><dt lang="ja">ありがとうございます</dt><dd>谢谢</dd></div><div><dt lang="ja">駅はどこですか</dt><dd>车站在哪里？</dd></div><div><dt lang="ja">写真を撮ってもいいですか</dt><dd>可以拍照吗？</dd></div><div><dt lang="ja">お会計をお願いします</dt><dd>请结账</dd></div></dl></div>
        <div className="practical-grid"><div><span>到着</span><h3>抵达</h3><p>新干线直达京都站；从关西机场可乘铁路或巴士。票务、班次和行李规则会变化，请按抵达日期查询。</p></div><div><span>移動</span><h3>移动</h3><p>优先组合铁路与地铁，繁忙时段减少依赖市巴士；官方路线与票券信息见 <a href="https://kyoto.travel/en/getting-around/" target="_blank" rel="noreferrer">Kyoto Travel ↗</a>。</p></div><div><span>マナー</span><h3>礼仪</h3><p>尊重居民区与私人道路，不追随或擅自拍摄艺伎艺舞伎；出发前阅读 <a href="https://kyoto.travel/en/responsible-travel/" target="_blank" rel="noreferrer">京都负责任旅行指南 ↗</a>。</p></div></div>
      </section>

      <footer><div className="footer-mark">京</div><div><p className="footer-title" lang="ja">次の季節に、また京都で。</p><p>愿你记住的不只是金阁与鸟居，也有竹叶被风翻动的声音，以及一碗汤豆腐升起的白雾。</p></div><div className="sources"><span>出典 · 资料来源</span><a href="https://kyoto.travel/en/" target="_blank" rel="noreferrer">Kyoto City Official Travel Guide</a><a href="https://kyoto.travel/en/destinations/kiyomizudera-temple/" target="_blank" rel="noreferrer">Kiyomizu-dera</a><a href="https://kyoto.travel/en/see-and-do/foodculture.html" target="_blank" rel="noreferrer">Kyoto Food Culture</a><a href="https://kyoto.travel/en/responsible-travel/" target="_blank" rel="noreferrer">Responsible Travel</a></div><p className="colophon">CURATED AND ILLUSTRATED · MMXXVI</p></footer>
    </div>
  );
}
