function LocalName({ local, zh }: { local: string; zh: string }) {
  return <span className="bilingual-name"><span lang="fr">{local}</span><small>{zh}</small></span>;
}

function Note({ children, no }: { children: React.ReactNode; no: string }) {
  return <aside className="margin-note"><span>{no}</span><p>{children}</p></aside>;
}

export default function ParisGuide({ theme }: { theme: "vintage" | "modern" }) {
  return (
    <div className="book-pages paris-book">
      <header className="masthead"><div className="crumb"><span>FRANCE</span><i>◆</i><span>ÎLE-DE-FRANCE</span><i>◆</i><b>PARIS</b></div><p>{theme === "modern" ? "ÉDITION PHOTO · 现代影像版" : "CARNET DU VOYAGEUR · 旅行者版本"}</p></header>

      <section id="prologue" className="chapter hero-chapter">
        <div className="hero-title"><p className="eyebrow">LA VILLE QUI SAIT FAIRE UNE PAUSE</p><h2><span lang="fr">Paris</span><small>巴黎</small></h2><p className="hero-subtitle">铁塔负责远望，街角负责让人停下</p></div>
        <figure className="hero-figure"><img src={theme === "modern" ? "/images/paris-hero-modern.png" : "/images/paris-hero-vintage.png"} alt={theme === "modern" ? "生成的现代旅行摄影风格巴黎塞纳河、石桥与埃菲尔铁塔" : "美好年代旅行版画风格的巴黎塞纳河与埃菲尔铁塔"} /><figcaption><b>图版 I</b><span><i lang="fr">La Seine et la tour Eiffel</i> · 塞纳河与埃菲尔铁塔</span><small>河流把城市展开，桥梁负责把每一页重新接上。</small></figcaption></figure>
        <div className="prologue-grid"><div className="lead-copy"><span className="drop-cap">巴</span><p>黎很会安排视线：一条大道把纪念碑放在尽头，一座桥把穹顶框进拱洞，塞纳河又让石头的重量在水面变轻。可真正让人惦记的，往往是一扇刚开门的面包店和露台上无人催促的一杯咖啡。</p><p>不必一直追逐“最经典”的角度。上午沿右岸看权力与收藏，午后越过桥去左岸读书、散步，傍晚交给河岸。巴黎的优雅并非把行程塞满，而是知道何时停顿。</p></div><blockquote><span>“</span><p lang="fr">Paris se révèle entre deux rendez-vous, au moment où l’on cesse de se presser.</p><small>巴黎常在两个约会之间显露自己——就在你不再赶路的时候。</small></blockquote><div className="fact-card"><p className="fact-label">EN UN COUP D’ŒIL · 扉页速览</p><dl><div><dt>最佳步调</dt><dd>3—4 日</dd></div><div><dt>城市气质</dt><dd>精致、松弛、善辩</dd></div><div><dt>适合时节</dt><dd>晚春 / 初秋</dd></div><div><dt>不可错过</dt><dd>沿塞纳河走到天黑</dd></div></dl></div></div>
      </section>

      <section id="cultura" className="chapter chapter-cultura">
        <div className="chapter-heading"><p>CHAPITRE UN · 第一章</p><h2><span lang="fr">Culture</span><small>人文 · 河岸与目光</small></h2><span className="page-no">01</span></div>
        <article className="feature-duomo"><div className="feature-number">I</div><div><p className="category">FER & HORIZON · 钢铁与远景</p><h3><LocalName local="La tour Eiffel" zh="埃菲尔铁塔" /></h3><p className="standfirst">为 1889 年世界博览会而生的钢铁结构，后来成为巴黎最擅长切换远近的取景框。</p><div className="columns"><p>从夏乐宫看全貌，从战神广场看结构，登塔则把塞纳河与奥斯曼街区重新排成地图。它不是孤立的地标，而是理解巴黎轴线、桥梁与城市尺度的最佳起点。</p><p>热门时段应尽量通过官方渠道预约。若不登塔，清晨沿比尔哈凯姆桥与河岸散步，也能避开最拥挤的人流，把钢铁轮廓留在柔和光线里。</p></div><div className="visit-strip"><span><b>建议</b> 清晨或日落前</span><span><b>留时</b> 2—3 小时</span><a href="https://www.toureiffel.paris/en" target="_blank" rel="noreferrer">官方网站 ↗</a></div></div><Note no="1889">埃菲尔铁塔为 1889 年巴黎世界博览会建造，临时工程最终成了城市象征。</Note></article>
        <div className="culture-mosaic"><article className="art-card last-supper"><p className="category">PALACE OF ART · 艺术宫殿</p><span className="art-index">02</span><h3><LocalName local="Musée du Louvre" zh="卢浮宫" /></h3><p>从古代文明到欧洲绘画，收藏规模足以让任何“看完”计划失效。更聪明的办法是提前选一个时代、几件核心作品，再给建筑和庭院留出注意力。</p><p className="tip">卢浮宫通常周二闭馆，官方建议提前预约；开放安排可能调整。</p><a href="https://www.louvre.fr/en/visit/hours-admission/tickets-and-prices" target="_blank" rel="noreferrer">MUSÉE DU LOUVRE ↗</a></article><article className="art-card brera-card"><p className="category">ISLAND · 城市原点</p><span className="art-index">03</span><h3><LocalName local="Notre-Dame de Paris" zh="巴黎圣母院" /></h3><p>西岱岛上的双塔、飞扶壁与彩窗见证城市如何从河中长大。走过主立面后继续绕到东侧，建筑的结构比正面更有力量。</p></article><article className="art-card scala-card"><p className="category">HILL & ATELIERS · 山丘与画室</p><span className="art-index">04</span><h3><LocalName local="Montmartre" zh="蒙马特" /></h3><p>避开最拥挤的广场，沿山坡寻找小葡萄园、画室旧址和居民街道；清晨的蒙马特比正午更接近街区本身。</p></article><article className="art-card castle-card paris-passage-card"><p className="category">PASSAGES · 室内街道</p><span className="art-index">05</span><h3><LocalName local="Passages couverts" zh="拱廊街" /></h3><p>玻璃顶、马赛克地面、旧书与小店把十九世纪的城市消费藏在街区内部。雨天从一条拱廊穿到另一条，巴黎会自动切换成室内版本。</p></article></div>
      </section>

      <section id="natura" className="chapter chapter-natura">
        <div className="chapter-heading"><p>CHAPITRE DEUX · 第二章</p><h2><span lang="fr">Nature</span><small>自然 · 河流与花园</small></h2><span className="page-no">02</span></div>
        <div className="nature-layout"><figure className="navigli-figure"><img src={theme === "modern" ? "/images/paris-nature-modern.png" : "/images/paris-nature-vintage.png"} alt={theme === "modern" ? "生成的现代旅行摄影风格塞纳河、树荫与巴黎圣母院" : "复古水彩旅行画风格的塞纳河岸与巴黎圣母院"} /><figcaption><b>图版 II</b><span><i lang="fr">Les quais de Seine</i> · 塞纳河岸</span></figcaption></figure><article className="navigli-copy"><p className="category">LE FLEUVE · 河流</p><h3><LocalName local="La Seine" zh="塞纳河" /></h3><p className="standfirst">巴黎最可靠的方向感不是指南针，而是河：右岸与左岸、岛屿与桥梁，都以水为坐标。</p><p>从西岱岛向西走，可经过新桥、卢浮宫与杜乐丽花园；向东则连接圣路易岛和玛黑区。早晨属于跑步者和送货车，黄昏属于倒影、长椅和不急着回去的人。</p><div className="time-note"><span>07:30</span><p><b lang="fr">Paris avant le café</b><small>第一杯咖啡前的河岸</small></p></div></article><Note no="2 RIVES">右岸与左岸不是两半城市，而是两种步行节奏；用桥来切换，不必执着直线。</Note></div>
        <div className="green-index"><article className="green-feature"><span className="botanical-mark">✦</span><p className="category">JARDIN · 花园</p><h3><LocalName local="Jardin du Luxembourg" zh="卢森堡公园" /></h3><p>树阵、喷泉、雕塑与绿色座椅共同组成巴黎式公共客厅。买一份简单午餐坐下，比急着赶下一站更像本地生活。</p><p className="green-tip">从拉丁区步行进入，离开时可沿圣日耳曼方向继续。</p></article><article><span className="mini-no">N. 02</span><h3><LocalName local="Jardin des Tuileries" zh="杜乐丽花园" /></h3><p>卢浮宫与协和广场之间的几何花园，是把艺术行程放松成散步的最好过渡。</p></article><article><span className="mini-no">N. 03</span><h3><LocalName local="Parc des Buttes-Chaumont" zh="肖蒙山丘公园" /></h3><p>坡地、湖面、洞穴与高处视野带来更野逸的城市绿地体验，也更接近东北巴黎的居民日常。</p></article></div>
      </section>

      <section id="sapori" className="chapter chapter-sapori">
        <div className="chapter-heading dark-heading"><p>CHAPITRE TROIS · 第三章</p><h2><span lang="fr">Saveurs</span><small>美食 · 黄油与火候</small></h2><span className="page-no">03</span></div>
        <div className="food-spread"><figure><img src={theme === "modern" ? "/images/paris-food-modern.png" : "/images/paris-food-vintage.png"} alt={theme === "modern" ? "生成的现代美食摄影风格巴黎可颂、法棍三明治、洋葱汤与水果挞" : "美好年代插画风格的巴黎小酒馆餐桌"} /><figcaption><b>图版 III</b><span><i lang="fr">À la table parisienne</i> · 巴黎餐桌</span></figcaption></figure><div className="food-intro"><p className="category">BEURRE & CROÛTE · 黄油与脆壳</p><h3>清晨听酥皮碎裂，<br />夜晚让一杯酒慢下来。</h3><p>巴黎味道不必昂贵：出炉的法棍、吧台咖啡、简单三明治和一碗热汤都能成为城市记忆。高级餐厅精于秩序，小酒馆则擅长让黄油、焦糖化洋葱与锅底肉汁直接说话。</p><p className="script-note" lang="fr">Bon appétit !</p><small>“祝你好胃口！” · 用餐前的日常祝语</small></div></div>
        <div className="dish-grid"><article className="dish-primary"><span className="dish-no">01</span><p className="category">MATIN · 清晨</p><h3><LocalName local="Croissant au beurre" zh="黄油可颂" /></h3><p>理想的可颂外壳轻脆、层次分明，内部带蜂窝状组织和温暖黄油香。找一间现场烘焙的面包店，趁热、空手吃完即可。</p></article><article><span className="dish-no">02</span><p className="category">BISTROT · 小酒馆</p><h3><LocalName local="Soupe à l’oignon" zh="法式洋葱汤" /></h3><p>耐心炒软的洋葱、浓汤、面包与焗奶酪构成深夜也可靠的一碗温热。</p></article><article><span className="dish-no">03</span><p className="category">SUR LE POUCE · 简餐</p><h3><LocalName local="Jambon-beurre" zh="火腿黄油法棍" /></h3><p>脆壳法棍、咸香火腿和黄油只有三件事，却能迅速检验面包与原料是否诚实。</p></article><article className="aperitivo-card paris-apero-card"><span className="dish-no">18:30</span><p className="category">RITUEL · 城市仪式</p><h3><LocalName local="L’apéritif" zh="开胃酒时光" /></h3><p>晚餐前点一杯酒或无酒精开胃饮，配橄榄与简单小食，观察街道比研究菜单更重要。露台座位的意义，就是允许人光明正大地走神。</p></article></div>
      </section>

      <section id="itinerario" className="chapter chapter-itinerary">
        <div className="chapter-heading"><p>CHAPITRE QUATRE · 第四章</p><h2><span lang="fr">Itinéraire</span><small>行程 · 48 小时</small></h2><span className="page-no">04</span></div>
        <div className="route-days"><article><header><span>JOUR</span><b>01</b><small>河岸与经典</small></header><ol><li><time>08:30</time><p><b lang="fr">Tour Eiffel</b><span>清晨看铁塔与战神广场</span></p></li><li><time>11:00</time><p><b lang="fr">Musée du Louvre</b><span>按主题选看收藏</span></p></li><li><time>15:30</time><p><b lang="fr">Île de la Cité</b><span>圣母院与两座岛</span></p></li><li><time>18:30</time><p><b lang="fr">Quais de Seine</b><span>沿河走进晚餐</span></p></li></ol></article><article><header><span>JOUR</span><b>02</b><small>花园与街区</small></header><ol><li><time>08:00</time><p><b lang="fr">Montmartre</b><span>在人群前登上山丘</span></p></li><li><time>12:00</time><p><b lang="fr">Passages couverts</b><span>拱廊、旧书与午餐</span></p></li><li><time>15:00</time><p><b lang="fr">Saint-Germain</b><span>书店与卢森堡公园</span></p></li><li><time>19:00</time><p><b lang="fr">Le Marais</b><span>街区晚餐与夜间漫步</span></p></li></ol></article></div>
        <div className="phrasebook"><div><p className="category">MOTS EN POCHE · 袖珍会话</p><h3 lang="fr">Une table pour deux, s’il vous plaît.</h3><p>请给我们一张两人桌。</p></div><dl><div><dt lang="fr">Bonjour</dt><dd>你好 / 日安</dd></div><div><dt lang="fr">Où est le métro ?</dt><dd>地铁在哪里？</dd></div><div><dt lang="fr">Deux billets, s’il vous plaît</dt><dd>请给我两张票</dd></div><div><dt lang="fr">L’addition, s’il vous plaît</dt><dd>请结账</dd></div></dl></div>
        <div className="practical-grid"><div><span>ARRIVER</span><h3>抵达</h3><p>戴高乐与奥利机场均有公共交通连接市区；线路、施工与运营安排以 <a href="https://www.ratp.fr/en/visiting-paris/transport-operating-hours-airport-links" target="_blank" rel="noreferrer">RATP 机场交通 ↗</a> 为准。</p></div><div><span>SE DÉPLACER</span><h3>移动</h3><p>核心区适合步行，跨区使用地铁、RER、公交与电车。票制可能调整，出发前查看 <a href="https://www.ratp.fr/en/titres-et-tarifs" target="_blank" rel="noreferrer">RATP 官方票务 ↗</a>。</p></div><div><span>RÉSERVER</span><h3>预约</h3><p>卢浮宫与埃菲尔铁塔应优先查看官方预约；博物馆常有固定闭馆日，临时展与夜场也会影响开放安排。</p></div></div>
      </section>

      <footer><div className="footer-mark">P</div><div><p className="footer-title" lang="fr">Paris vous attend au prochain coin de rue.</p><p>愿你记住的不只是铁塔，也有晨光里的面包香、河岸上一把空椅子，以及一次没有目的地的拐弯。</p></div><div className="sources"><span>SOURCES · 资料来源</span><a href="https://parisjetaime.com/eng/article/the-essentials-a264" target="_blank" rel="noreferrer">Paris je t’aime</a><a href="https://www.toureiffel.paris/en" target="_blank" rel="noreferrer">Tour Eiffel</a><a href="https://www.louvre.fr/en/visit/hours-admission/tickets-and-prices" target="_blank" rel="noreferrer">Musée du Louvre</a><a href="https://www.ratp.fr/en" target="_blank" rel="noreferrer">RATP</a></div><p className="colophon">CURATED AND ILLUSTRATED · MMXXVI</p></footer>
    </div>
  );
}
